clang-format action is failing. This PR replaces the action with clang-format from apt
Signed-off-by: Arrobo, Gabriel <gabriel.arrobo@intel.com>

diff --git a/.github/workflows/check-clang-format.yml b/.github/workflows/check-clang-format.yml
--- a/.github/workflows/check-clang-format.yml
+++ b/.github/workflows/check-clang-format.yml
@@ -1,5 +1,6 @@
-# SPDX-License-Identifier: Apache-2.0
+# SPDX-FileCopyrightText: 2026 Intel Corporation
 # Copyright 2025 Canonical Ltd.
+# SPDX-License-Identifier: Apache-2.0
 name: Clang-format check
 
 on:
@@ -14,7 +15,7 @@ on:
         description: "The major version of clang-format that you want to run the check on"
         required: false
         type: string
-        default: "12"
+        default: "14"
       check_path:
         description: |
           The path to the directory in the repo that should be checked for C/C++/Protobuf formatting.
@@ -36,9 +37,34 @@ jobs:
         with:
           ref: ${{ inputs.branch_name }}
 
-      - name: Clang-format check
-        uses: jidicula/clang-format-action@v4.16.0
-        with:
-          clang-format-version: ${{ inputs.clang_format_version }}
-          check-path: ${{ inputs.check_path }}
-          exclude-regex: ${{ inputs.exclude_regex }}
+      - name: Install clang-format
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y clang-format-${{ inputs.clang_format_version }}
+          sudo ln -sf /usr/bin/clang-format-${{ inputs.clang_format_version }} /usr/bin/clang-format
+
+      - name: Run clang-format check
+        run: |
+          CHECK_PATH="${{ inputs.check_path }}"
+          EXCLUDE_REGEX="${{ inputs.exclude_regex }}"
+
+          # Set default regex if empty
+          if [[ -z "$EXCLUDE_REGEX" ]]; then
+            EXCLUDE_REGEX="^$"
+          fi
+
+          # Find all C/C++/Protobuf files
+          INCLUDE_REGEX='^.*\.((((c|C)(c|pp|xx|\+\+)?$)|((h|H)h?(pp|xx|\+\+)?$))|(ino|pde|proto|cu))$'
+
+          # Find files and check formatting
+          EXIT_CODE=0
+          while IFS= read -r file; do
+            if ! echo "$file" | grep -Eq "$EXCLUDE_REGEX"; then
+              if ! clang-format --dry-run --Werror --style=file --fallback-style=llvm "$file"; then
+                echo "Failed on file: $file"
+                EXIT_CODE=1
+              fi
+            fi
+          done < <(find "$CHECK_PATH" -name .git -prune -o -regextype posix-egrep -regex "$INCLUDE_REGEX" -print)
+
+          exit $EXIT_CODE
